using CCL;
using CCL.GTAIV;
using IVSDKDotNet;
using IVSDKDotNet.Enums;
using IVSDKDotNet.Native;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Security.Policy;
using System.Text;
using System.Threading.Tasks;
using static IVSDKDotNet.Native.Natives;

namespace MissionStuff.ivsdk
{
    internal class GangRelationships
    {
        // IniShit
        private static bool spawnGangs;
        private static int timeToSpawn;
        private static float spawnDist;
        private static bool debug;

        // GangSpawnShit
        private static Vector3 spawnPos;
        private static Vector3 placeToSpawn;
        private static bool spawnGangMember;
        private static int randModel;
        private static int pedType;
        private static int gangModel;
        private static int gangPed;

        // OtherShit
        private static float gameProg;
        private static uint fTimer;
        public static void Init(SettingsFile settings)
        {
            spawnGangs = settings.GetBoolean("MAIN", "SpawnRandomGangs", false);
            timeToSpawn = settings.GetInteger("MAIN", "GangSpawnInterval", 15000);
            spawnDist = settings.GetInteger("MAIN", "GangSpawnDistance", 30);
            debug = settings.GetBoolean("MAIN", "SpawnGangsDebug", false);
        }
        public static void UnInit()
        {
        }
        private static void InitGangRelationships()
        {
            // Dislike relationship fix (based on info by Lord Criminal - creator of Potential Grim)
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_HATE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_PROSTITUTE);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_HATE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_PROSTITUTE);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_HATE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_PROSTITUTE);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_HATE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ITALIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_PROSTITUTE);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_HATE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_PROSTITUTE);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_HATE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_PROSTITUTE);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_HATE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_IRISH, (int)eRelationshipGroup.RELATIONSHIP_GROUP_PROSTITUTE);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_HATE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_JAMAICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_PROSTITUTE);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_HATE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_AFRICAN_AMERICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_PROSTITUTE);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_HATE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_PROSTITUTE);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_HATE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_PROSTITUTE);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_HATE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_PROSTITUTE);

            /*// Albanians
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ITALIAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_IRISH);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_JAMAICAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_AFRICAN_AMERICAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN);

            // Angels of Death
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ITALIAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_IRISH);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_JAMAICAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_AFRICAN_AMERICAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_RESPECT, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN);

            // Lost MC
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ITALIAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_IRISH);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_JAMAICAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_AFRICAN_AMERICAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN);

            // Italian Mob
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ITALIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ITALIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ITALIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ITALIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ITALIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ITALIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_IRISH);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ITALIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_JAMAICAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ITALIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_AFRICAN_AMERICAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ITALIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ITALIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ITALIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN);

            // Russian Mafia 1
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ITALIAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_RESPECT, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_IRISH);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_JAMAICAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_AFRICAN_AMERICAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN);

            // Russian Mafia 2
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ITALIAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_RESPECT, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_IRISH);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_JAMAICAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_AFRICAN_AMERICAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN);

            // Irish Gang
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_IRISH, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_IRISH, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_IRISH, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_IRISH, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ITALIAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_IRISH, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_IRISH, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_RESPECT, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_IRISH, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_JAMAICAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_IRISH, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_AFRICAN_AMERICAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_IRISH, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_IRISH, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_IRISH, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN);

            // Jamaican Yardies
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_JAMAICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_JAMAICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_JAMAICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_JAMAICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ITALIAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_JAMAICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_JAMAICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_RESPECT, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_JAMAICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_IRISH);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_JAMAICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_AFRICAN_AMERICAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_JAMAICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_JAMAICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_RESPECT, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_JAMAICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN);

            // Hustlers
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_AFRICAN_AMERICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_AFRICAN_AMERICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_AFRICAN_AMERICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_AFRICAN_AMERICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ITALIAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_AFRICAN_AMERICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_AFRICAN_AMERICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_AFRICAN_AMERICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_IRISH);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_AFRICAN_AMERICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_JAMAICAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_AFRICAN_AMERICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_AFRICAN_AMERICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_AFRICAN_AMERICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN);

            // Korean Mob
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ITALIAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_IRISH);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_JAMAICAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_AFRICAN_AMERICAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_RESPECT, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN);

            // Triads
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_RESPECT, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ITALIAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_IRISH);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_JAMAICAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_AFRICAN_AMERICAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_RESPECT, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN);

            // Spanish Lords
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ITALIAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_IRISH);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_RESPECT, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_JAMAICAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_AFRICAN_AMERICAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_LIKE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN);
            ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
            SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE);
            */
        }
        private static void SpawnTheFuckingPed(int pType, int pModel, Vector3 pLoc)
        {
            REQUEST_MODEL(pModel);
            if (!HAS_MODEL_LOADED(pModel))
                return;
            else
            {
                spawnGangMember = false;
                CREATE_CHAR(pType, pModel, pLoc, out gangPed, true);
                MARK_MODEL_AS_NO_LONGER_NEEDED(pModel);
                MARK_CHAR_AS_NO_LONGER_NEEDED(gangPed);
                if (debug)
                IVGame.ShowSubtitleMessage("Ped Spawned");
            }
        }
        private static void SpawnRandomGangMembers(int gangType)
        {
            switch (gangType)
            {
                case 0:
                    pedType = (int)ePedType.PED_TYPE_ALBANIAN_GANG;
                    randModel = GENERATE_RANDOM_INT_IN_RANGE(0, 4);
                    switch (randModel)
                    {
                        case 0:
                            gangModel = GET_HASH_KEY("m_y_galb_lo_01");
                            break;
                        case 1:
                            gangModel = GET_HASH_KEY("m_y_galb_lo_02");
                            break;
                        case 2:
                            gangModel = GET_HASH_KEY("m_y_galb_lo_03");
                            break;
                        case 3:
                            gangModel = GET_HASH_KEY("m_y_galb_lo_04");
                            break;
                    }
                    break;
                case 1:
                    pedType = (int)ePedType.PED_TYPE_ANGELS_OF_DEATH;
                    randModel = GENERATE_RANDOM_INT_IN_RANGE(0, 4);
                    switch (randModel)
                    {
                        case 0:
                            gangModel = GET_HASH_KEY("m_m_gbik_lo_03");
                            break;
                        case 1:
                            gangModel = GET_HASH_KEY("m_y_gbik02_lo_02");
                            break;
                        case 2:
                            gangModel = GET_HASH_KEY("m_y_gbik_hi_01");
                            break;
                        case 3:
                            gangModel = GET_HASH_KEY("m_y_gbik_hi_02");
                            break;
                    }
                    break;
            }
            spawnGangMember = true;
        }
        public static void Tick()
        {
            SET_PLAYER_CAN_BE_HASSLED_BY_GANGS(Main.PlayerIndex, false);

            /*if (spawnGangMember)
                SpawnTheFuckingPed(pedType, gangModel, placeToSpawn);*/

            if (IS_PLAYER_CONTROL_ON(Main.PlayerIndex))
            {
                /*if (spawnGangs && Main.gTimer >= fTimer + timeToSpawn)
                {
                    spawnPos = Main.PlayerPos.Around(spawnDist);
                    GET_CLOSEST_CHAR(spawnPos.X, spawnPos.Y, spawnPos.Z, 5.0f, 1, 0, out int closestPed);
                    if (DOES_CHAR_EXIST(closestPed) && closestPed > 0)
                    {
                        if (!IS_CHAR_SITTING_IN_ANY_CAR(closestPed) && !IS_CHAR_SITTING_IDLE(closestPed) && !IS_CHAR_USING_ANY_SCENARIO(closestPed) && IS_CHAR_ON_SCREEN(closestPed))
                        {
                            GET_CHAR_COORDINATES(closestPed, out placeToSpawn);
                            if ((Main.PlayerPos - placeToSpawn).Length() >= spawnDist)
                            {
                                GET_GAME_TIMER(out fTimer);
                                if (debug)
                                IVGame.ShowSubtitleMessage("Spawning ped..." + (Main.PlayerPos - placeToSpawn).Length());
                                SpawnRandomGangMembers(GENERATE_RANDOM_INT_IN_RANGE(0, 2));
                            }
                        }
                    }
                }*/

                if (GET_FLOAT_STAT(0) != gameProg)
                {
                    InitGangRelationships();

                    if (GET_FLOAT_STAT(3) > 25)
                    {
                        ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
                        SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_ALBANIAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_PLAYER);
                    }
                    if (GET_FLOAT_STAT(8) > 95)
                    {
                        ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
                        SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_PLAYER);
                        ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
                        SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_RUSSIAN2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_PLAYER);
                    }
                    if (GET_FLOAT_STAT(10) > 70)
                    {
                        ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
                        SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_PLAYER);
                        ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
                        SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER1, (int)eRelationshipGroup.RELATIONSHIP_GROUP_PLAYER);
                    }
                    if (GET_FLOAT_STAT(13) > 70)
                    {
                        ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
                        SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_PUERTO_RICAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_PLAYER);
                    }
                    if (GET_FLOAT_STAT(22) > 30)
                    {
                        ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
                        SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_CHINESE_JAPANESE, (int)eRelationshipGroup.RELATIONSHIP_GROUP_PLAYER);
                    }
                    if (GET_FLOAT_STAT(23) > 90)
                    {
                        ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
                        SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_BIKER2, (int)eRelationshipGroup.RELATIONSHIP_GROUP_PLAYER);
                    }
                    if (GET_FLOAT_STAT(28) > 60)
                    {
                        ALLOW_GANG_RELATIONSHIPS_TO_BE_CHANGED_BY_NEXT_COMMAND(true);
                        SET_RELATIONSHIP((uint)eRelationship.RELATIONSHIP_NEUTRAL, (int)eRelationshipGroup.RELATIONSHIP_GROUP_GANG_KOREAN, (int)eRelationshipGroup.RELATIONSHIP_GROUP_PLAYER);
                    }
                    gameProg = GET_FLOAT_STAT(0);
                }
            }
        }
    }
}
